spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatserver
    username: postgres
    password: pass@123
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

    consumer:
      group-id: canto-chat
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        "[spring.json.value.default.type]": "com.englabs.chatServer.conversation.dto.event.ChatMessageEvent"
        "[spring.json.trusted.packages]": "com.englabs.chatServer"

app:
  cors:
    allowed-origins:
      - http://localhost:5173

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.zaxxer.hikari: DEBUG